version: "3.8"
volumes:
  grafana_data:
  logs:
  datadir:
  gwc_config:
  gwc:
  netcfd:
  grib_cache:
  data_pg:
  backend_mapas:
networks:
  net:
    name: net
    driver: bridge

services:

  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: benefrancis/mapas:latest
    container_name: api4${CONTAINER_NAME:-} # Utilizando a variável de ambiente e um valor padrão caso ela não exista
    deploy:
      resources:
        limits:
          memory: 3G
    ports:
      - ${SERVER_PORT:-80}:${SERVER_PORT:-80}
    depends_on:
      - db
    environment:
      JAVA_OPTS: -Xms1g -Xmx2g
      POSTGRES_SERVER: db
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_NAME: ${POSTGRES_NAME:-mapas}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./src/main/resources/templates:/templates
      - ./src/main/resources/static:/static
      - logs:/data/logs/mapas
      - backend_mapas:/assets
    command: java -jar /app.jar # Comando para iniciar sua aplicação
    networks:
      - net
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-80}/actuator/health" ] #Healthcheck para sua aplicação
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  geoserver:
    image: geosolutionsit/geoserver:2.26.x
    container_name: geoserver4${CONTAINER_NAME:-}  # Utilizando a variável de ambiente e um valor padrão caso ela não exista
    restart: always
    environment:
      POSTGRES_JNDI_ENABLED: true
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mapas
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      GEOSERVER_ADMIN_USERNAME: "admin" # Troque esta senha
      GEOSERVER_ADMIN_PASSWORD: "geoserver" # Troque esta senha
      GEOSERVER_LOG_DIR: /var/log/geoserver
      GEOSERVER_DATA_DIR: /var/lib/geoserver_data
      GEOWEBCACHE_CONFIG_DIR: /var/lib/geowebcache/config
      GEOWEBCACHE_CACHE_DIR: /var/lib/geowebcache/cache
      NETCDF_DATA_DIR: /var/lib/netcdf
      GRIB_CACHE_DIR: /var/lib/grib
    volumes:
      - logs:/var/log/geoserver
      - datadir:/var/lib/geoserver_data
      - gwc_config:/var/lib/geowebcache/config
      - gwc:/var/lib/geowebcache/cache
      - netcfd:/var/lib/netcdf
      - grib_cache:/var/lib/grib
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on:
      - db
    command: [ "catalina.sh", "run" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/geoserver/rest/about/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    image: postgis/postgis:9.5-2.5
    container_name: db4${CONTAINER_NAME:-} # Utilizando a variável de ambiente e um valor padrão caso ela não exista
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mapas
    ports:
      - "5432:5432"
    volumes:
      - data_pg:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq4${CONTAINER_NAME:-}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net
    volumes:
      - ./rabbitmq_setup.sh:/docker-entrypoint-initdb.d/rabbitmq_setup.sh
      - ./erlang.config:/etc/rabbitmq/erlang.config
    healthcheck:
      test: [ "CMD", "curl", "-f", "-u", "rabitmq:rabitmq", "http://localhost:15672/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    environment:
      RABBITMQ_ADVANCED_CONFIG: |
        [
            {
               deprecated_features,
               [{permit,
                [{management_metrics_collection, true}]
                }]
             }
        ].
      ERL_FLAGS: "+S 1 +K true +A30 +Bc16384 --enable-feature all"
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus4${CONTAINER_NAME:-}  # Utilizando a variável de ambiente e um valor padrão caso ela não exista
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - net
    depends_on:
      - geoserver
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/-/healthy" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  grafana:
    image: grafana/grafana:9.1.7
    container_name: grafana4${CONTAINER_NAME:-}  # Utilizando a variável de ambiente e um valor padrão caso ela não exista
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - net
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s