 # Use a versão correta da imagem do PostGIS
FROM postgis/postgis:15-3.4
RUN apt-get update && \
    apt-get --reinstall install -y postgis postgresql-15-postgis-3 && \
    rm -rf /var/lib/apt/lists/*