app:
  base-url: "https://cnuc-backend.mma.gov.br/api/v1/uc/"


server:
  port: 90
  servlet:
    context-path: /
spring:
  application:
    name: mapas
  profiles:
    active: ${PROFILE}

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
    template-resolver-order: 1
    servlet:
      content-type: text/html
    check-template: true

  web:
    locale-resolver: accept_header
    locale: pt_BR

  config:
    import: optional:file:.env[.properties]

  # REDIS
  cache:
    type: redis
    cache-names: mapas-cache
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:root}
      cache-null-values: true

# Prometheus Configuration
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    br.mp.mpf.aguaboa: DEBUG
    web: DEBUG
    org.thymeleaf: DEBUG
  file:
    name: "/data/logs/mapas/mapas.log"
  pattern:
    file:
      # Formato do log para arquivos
      - "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    console:
      # Formato do log para o console (opcional)
      - "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  logback:
    # Configuração adicional para a rotação de logs
    rollingpolicy:
      file:
        max-size: 10MB
        max-history: 30
    encoder:
      pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"